import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
const source=fs.readFileSync(process.env.LABEL_SHEET_TEST_SOURCE||new URL('../src/index.template.html',import.meta.url),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
function functionSource(name){const lines=source.split('\n');const start=lines.findIndex(line=>new RegExp(`^      (?:async )?function ${name}\\(`).test(line));if(start<0)return '';if(!lines[start].trimEnd().endsWith('{'))return lines[start];const end=lines.findIndex((line,i)=>i>start&&/^      }\s*$/.test(line));assert.ok(end>start,name);return lines.slice(start,end+1).join('\n');}
function context(){
  const nodes=new Map();const c=vm.createContext({console,JSON,Date,setTimeout,clearTimeout});
  class Element {constructor(id=''){this.id=id;this.value='';this.dataset={};this.attrs={};this.style={};this.hidden=false;this.isContentEditable=false;this.parentElement=null;this.listeners={};this.classList={toggle(){},add(){},remove(){}};}
    setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];}setCustomValidity(v){this.validationMessage=v;}focus(){c.document.activeElement=this;}addEventListener(k,f){this.listeners[k]=f;}append(){}replaceChildren(){}querySelector(){return null;}closest(selector){if(selector==='[data-sheet-slot]')return this.attrs['data-sheet-slot']?this:null;if(selector==='.field')return this.parentElement;if(selector.includes('#labelEditorSvg')&&this.editor)return nodes.get('#labelEditorSvg');return null;}}
  class Input extends Element{}class Textarea extends Element{}class Select extends Element{}
  c.Element=Element;c.HTMLElement=Element;c.HTMLInputElement=Input;c.HTMLTextAreaElement=Textarea;c.HTMLSelectElement=Select;c.$=key=>{if(!nodes.has(key))nodes.set(key,new Element(key));return nodes.get(key);};c.$$=selector=>selector==='[data-dimension], [data-integer]'?[...nodes.values()].filter(n=>n.dataset.dimension||n.dataset.integer):[];
  c.document={activeElement:null,querySelector:()=>c.modal?{}:null,createElement:()=>new Element(),body:new Element()};
  c.t=k=>k;c.AppToast={show:o=>{c.toast=o;},dismiss(){}};c.refreshPdfValidity=()=>true;c.invalidateGeneratedPdf=()=>{};
  c.persistSettings=()=>{c.persisted=clone(c.state.settings);};c.writeStorage=()=>true;c.storageKeys={unit:'unit'};c.renderPresetOptions=()=>{};c.renderPaperLayout=()=>{};c.renderLayoutDraftFeedback=()=>{};c.renderOutputPage=()=>{};c.closeTouchContextMenu=()=>{};
  for(const marker of ['LABEL_SHEET_CORE','LABEL_EDITOR_CORE','SHEET_COMPOSITION_CORE'])vm.runInContext(source.split(`/* ${marker}:BEGIN */`)[1].split(`/* ${marker}:END */`)[0],c);
  c.defaultSettings=clone(c.LabelSheetCore.builtInPresets()[0].settings);c.state={settings:clone(c.defaultSettings),activePage:'labelPage'};c.layoutDrafts={};c.unit='mm';c.sheetState={usedFirstPage:[2],pageIndex:0};c.dataState={mode:'repeat',repeatCount:1,rows:[]};c.editorState={elements:[c.LabelEditorCore.createTextElement({id:'original',labelWidth:66,labelHeight:33.9,text:'Original'})],selectedId:'original',history:[[]],historyIndex:0,deletedSnapshot:null};
  for(const name of ['cancelLongPress','cancelEditorInteraction','hasPendingLayoutDrafts','resetLayoutDrafts','layoutDraftSettings','commitLayoutDrafts','updateLayoutInput','updateDimensionInput','updateIntegerInput','setDisplayUnit','setPaperType','setSettings','currentSettingsSnapshot','cloneEditorElements','sameSnapshot','selectedElement','editorBounds','clampEditorElements','updateHistoryButtons','pushEditorHistory','restoreHistory','undoEditor','redoEditor','restoreDeletedElement','deleteSelectedElement','sheetItemCount','sheetComposition','handleEditorKeydown','focusLabelCanvas','toggleUsedSlot']){const f=functionSource(name);if(f)vm.runInContext(f,c);}
  c.renderLabelEditor=()=>{};c.render=()=>{c.clampEditorElements();c.sheetComposition();};c.renderSheetPage=()=>{c.document.activeElement=c.document.body;};c.nudgeSelected=(x,y)=>{c.nudged=[x,y];};
  c.input=(key,value,integer=false)=>{const i=new Input(key);i.dataset[integer?'integer':'dimension']=key;i.value=value;i.parentElement=new Element();nodes.set('#'+key,i);return i;};
  c.key=(key,target,extra={})=>{const e={key,target,preventDefault(){this.prevented=true;},...extra};c.handleEditorKeydown(e);return e;};c.$('#labelEditorSvg');c.element=()=>new Element();c.inputClass=Input;c.nodes=nodes;return c;
}
test('empty, intermediate smaller and fractional dimension typing leaves committed work intact',()=>{const c=context(),before=clone(c.editorState.elements),settings=clone(c.state.settings),history=clone(c.editorState.history);const input=c.input('labelWidth','');for(const text of ['','6','66.','66.0']){input.value=text;c.updateDimensionInput(input);assert.deepEqual(clone(c.state.settings),settings);assert.deepEqual(clone(c.editorState.elements),before);assert.deepEqual(clone(c.sheetState.usedFirstPage),[2]);assert.deepEqual(clone(c.editorState.history),history);assert.equal(c.persisted,undefined);}input.value='66';c.updateDimensionInput(input,{commit:true});assert.deepEqual(clone(c.editorState.elements),before);assert.deepEqual(clone(c.sheetState.usedFirstPage),[2]);});
test('valid intentional shrink clamps only at commit and retains used positions',()=>{const c=context(),input=c.input('labelWidth','30');c.updateDimensionInput(input);assert.equal(c.state.settings.labelWidth,66);c.updateDimensionInput(input,{commit:true});assert.equal(c.state.settings.labelWidth,30);assert.ok(c.editorState.elements[0].x+c.editorState.elements[0].width<=30);assert.deepEqual(clone(c.sheetState.usedFirstPage),[2]);assert.equal(c.persisted.labelWidth,30);});
test('invalid overflow and integer drafts never persist or discard work and can be corrected together',()=>{const c=context(),before=clone(c.editorState.elements);const width=c.input('labelWidth','100');c.updateDimensionInput(width,{commit:true});assert.equal(c.state.settings.labelWidth,66);const cols=c.input('columns','2',true);c.updateIntegerInput(cols,{commit:true});assert.equal(c.state.settings.labelWidth,100);assert.equal(c.state.settings.columns,2);assert.deepEqual(clone(c.editorState.elements),before);const rows=c.input('rows','',true);c.updateIntegerInput(rows,{commit:true});assert.equal(c.state.settings.rows,8);rows.value='2.5';c.updateIntegerInput(rows,{commit:true});assert.equal(c.state.settings.rows,8);rows.value='8';c.updateIntegerInput(rows,{commit:true});assert.equal(c.state.settings.rows,8);});
test('reading an invalid composition never normalizes away stored used slots',()=>{const c=context();c.state.settings.labelWidth=0;c.sheetComposition();assert.deepEqual(clone(c.sheetState.usedFirstPage),[2]);});
test('inches commit physical dimensions and unit switching rejects unresolved invalid drafts',()=>{const c=context();c.unit='in';const input=c.input('labelWidth','2');c.updateDimensionInput(input,{commit:true});assert.equal(c.state.settings.labelWidth,50.8);input.value='';c.updateDimensionInput(input);assert.equal(c.setDisplayUnit('mm'),false);assert.equal(c.unit,'in');input.value='2';c.updateDimensionInput(input,{commit:true});assert.equal(c.setDisplayUnit('mm'),true);assert.equal(c.state.settings.labelWidth,50.8);});
for(const page of ['paperPage','sheetPage','outputPage'])test(`shortcuts do not edit a hidden label on ${page}`,()=>{const c=context();c.state.activePage=page;const target=c.element();target.editor=true;const before=clone(c.editorState.elements);for(const key of ['Delete','Backspace','ArrowRight','Escape'])assert.equal(c.key(key,target).prevented,undefined);c.key('z',target,{ctrlKey:true});assert.deepEqual(clone(c.editorState.elements),before);assert.equal(c.editorState.selectedId,'original');assert.equal(c.nudged,undefined);});
test('editor canvas owns shortcuts; navigation, buttons, text inputs, contenteditable and dialogs do not',()=>{for(const kind of ['navigation','button','input','contenteditable','modal']){const c=context(),before=clone(c.editorState.elements);const target=kind==='input'?new c.inputClass():c.element();if(kind==='modal'){target.editor=true;c.modal=true;}if(kind==='contenteditable'){target.editor=true;target.isContentEditable=true;}c.key('Delete',target);assert.deepEqual(clone(c.editorState.elements),before,kind);}const c=context(),target=c.element();target.editor=true;assert.equal(c.key('ArrowRight',target).prevented,true);assert.deepEqual(c.nudged,[.2,0]);c.key('Delete',target);assert.equal(c.editorState.elements.length,0);});
test('slot toggle restores focus to the same logical position only when the slot owned focus',()=>{const c=context(),old=c.element();old.setAttribute('data-sheet-slot','2');c.document.activeElement=old;const replacement=c.$('#sheetPreviewSvg [data-sheet-slot="2"]');c.toggleUsedSlot(2);assert.deepEqual(clone(c.sheetState.usedFirstPage),[]);assert.equal(c.document.activeElement,replacement);const unrelated=c.element();c.document.activeElement=unrelated;c.toggleUsedSlot(2);assert.notEqual(c.document.activeElement,replacement);});
test('keyboard undo retires the delete toast and stale toast cannot duplicate identities',()=>{const c=context();c.pushEditorHistory();c.deleteSelectedElement();const action=c.toast.onAction;c.undoEditor();action();assert.deepEqual(c.editorState.elements.map(x=>x.id),['original']);assert.equal(c.editorState.deletedSnapshot,null);});
test('new edit retires old delete toast while immediate toast undo remains available',()=>{const c=context();c.pushEditorHistory();c.deleteSelectedElement();c.toast.onAction();assert.equal(c.editorState.elements.length,1);c.deleteSelectedElement();const action=c.toast.onAction;c.editorState.elements.push({id:'new'});c.pushEditorHistory();action();assert.deepEqual(clone(c.editorState.elements),[{id:'new'}]);});
test('empty paper draft renders finite preview geometry',()=>{const c=context();vm.runInContext(functionSource('renderPreview'),c);c.document.createElementNS=()=>c.element();const draft={...c.state.settings,paperType:'custom',paperWidth:NaN};c.renderPreview(c.LabelSheetCore.computeLayout(draft),draft);assert.doesNotMatch(c.$('#paperPreviewSvg').getAttribute('viewBox'),/NaN|Infinity/);});
test('inch display never relabels millimetre print calibration controls',()=>{const c=context(),paper=c.element(),offset=c.element();paper.textContent='mm';offset.textContent='mm';c.unit='in';c.unitLabel=()=>c.unit;c.$$=selector=>selector==='.unit-suffix:not(.font-size-suffix)'?[paper,offset]:selector==='#paperPage .unit-suffix'?[paper]:[];vm.runInContext(functionSource('renderInputs'),c);c.renderInputs();assert.equal(paper.textContent,'in');assert.equal(offset.textContent,'mm');});
test('paper type changes can remain drafts while correcting a newly overflowing grid',()=>{const c=context(),before=clone(c.editorState.elements);c.renderInputs=()=>{};c.setPaperType('letter');assert.equal(c.state.settings.paperType,'a4');assert.equal(c.layoutDraftSettings().paperType,'letter');assert.equal(c.layoutDraftSettings().paperHeight,279.4);const rows=c.input('rows','7',true);c.updateIntegerInput(rows,{commit:true});assert.equal(c.state.settings.paperType,'letter');assert.equal(c.state.settings.paperHeight,279.4);assert.deepEqual(clone(c.editorState.elements),before);assert.deepEqual(clone(c.sheetState.usedFirstPage),[2]);});
test('custom paper selection preserves pending numeric edits and known-size changes stay exact in inches',()=>{const c=context();c.renderInputs=()=>{};const width=c.input('labelWidth','100');c.updateDimensionInput(width,{commit:true});c.setPaperType('custom');assert.equal(c.layoutDraftSettings().labelWidth,100);const cols=c.input('columns','2',true);c.updateIntegerInput(cols,{commit:true});assert.equal(c.state.settings.paperType,'custom');assert.equal(c.state.settings.labelWidth,100);c.unit='in';c.setPaperType('a4');assert.equal(c.state.settings.paperWidth,210);assert.equal(c.state.settings.paperHeight,297);});
