import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
const source=fs.readFileSync(process.env.LABEL_SHEET_TEST_SOURCE||new URL('../src/index.template.html',import.meta.url),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
// Compile complete production functions, including multiline bodies with compact first lines.
function functionSource(name){const lines=source.split('\n'),start=lines.findIndex(line=>new RegExp(`^      (?:async )?function ${name}\\(`).test(line));if(start<0)return '';for(let end=start+1;end<=lines.length;end++){const value=lines.slice(start,end).join('\n');try{new vm.Script(`(${value})`);return value;}catch{}}throw new Error(name);}
function harness(){
  const nodes=new Map(),geometry=[],timers=new Map();let timerId=0;
  const c=vm.createContext({console,JSON,Date,performance:{now:()=>1000},setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id)});
  class Element{constructor(id=''){this.id=id;this.value='';this.dataset={};this.attrs={};this.style={};this.listeners={};this.children=[];this.hidden=false;this.disabled=false;this.classList={toggle(){},add(){},remove(){},contains(){return false;}};}setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];}setCustomValidity(v){this.validationMessage=v;}addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}fire(k,extra={}){for(const fn of this.listeners[k]||[])fn({target:this,...extra});}focus(){c.document.activeElement=this;}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}querySelector(s){return s==='.layout-input-error'?this.children.find(x=>x.className==='layout-input-error'):null;}closest(s){if(s==='.field')return this.parentElement;if(s==='#labelEditorSvg')return this.editor?c.$('#labelEditorSvg'):null;if(s==='[data-element-id]')return this.dataset.elementId?this:null;if(s==='[data-element-hitbox]')return this.dataset.elementId?this:null;return null;}hasPointerCapture(id){return this.capture===id;}setPointerCapture(id){this.capture=id;}releasePointerCapture(id){if(this.capture===id)this.capture=null;}}
  class Input extends Element{}class Textarea extends Element{}class Select extends Element{}
  Object.assign(c,{Element,HTMLElement:Element,HTMLInputElement:Input,HTMLTextAreaElement:Textarea,HTMLSelectElement:Select,$:key=>{if(!nodes.has(key))nodes.set(key,new Element(key));return nodes.get(key);},$$:s=>s==='[data-editor-geometry]'?geometry:[],document:{activeElement:null,querySelector:()=>null,createElement:()=>new Element(),getElementById:id=>c.$('#'+id),body:new Element()},window:{scrollTo(){},matchMedia:()=>({matches:false})},requestAnimationFrame:fn=>fn(),t:k=>k,AppToast:{show(){}},unit:'mm',layoutDrafts:{},importState:{dataRequest:0,projectRequest:0,imageRequest:0},projectFileName:'labels.labelsheet.json',storageKeys:{unit:'unit'},writeStorage(){},persistSettings(){},renderPresetOptions(){},renderInputs(){},renderPaperLayout(){},renderSheetPage(){},renderOutputPage(){},renderDataFieldSelect(){},currentDataRow:()=>null,codeValidation:()=>({level:'ok',message:''}),DOUBLE_CLICK_MS:300,LONG_PRESS_MS:500,LONG_PRESS_MOVE_PX:8,SNAP_TOLERANCE_MM:1});
  for(const marker of ['LABEL_SHEET_CORE','LABEL_EDITOR_CORE','DATA_MERGE_CORE','BARCODE_MEDIA_CORE','SHEET_COMPOSITION_CORE','PDF_OUTPUT_CORE','PROJECT_FILE_CORE'])vm.runInContext(source.split(`/* ${marker}:BEGIN */`)[1].split(`/* ${marker}:END */`)[0],c);
  c.defaultSettings=clone(c.LabelSheetCore.builtInPresets()[0].settings);c.state={settings:clone(c.defaultSettings),activePage:'labelPage'};
  c.editorState={elements:[{...c.LabelEditorCore.createTextElement({id:'original',labelWidth:66,labelHeight:33.9,text:'Original'}),x:1.125,y:2.25,sourceType:'fixed',fieldName:''}],selectedId:'original',history:[],historyIndex:-1,interaction:null,longPress:null,panInteraction:null,lastTextPointer:{id:'',at:0},snapGuides:[],snapEnabled:false,zoom:100};
  c.dataState={mode:'repeat',repeatCount:1,headers:[],rows:[],rowIndex:0};c.sheetState={usedFirstPage:[],pageIndex:0};c.outputState={offsetX:0,offsetY:0,busy:false,generation:0,sourceFingerprint:null,generatedBlob:null};
  for(const [key,id] of Object.entries({x:'elementX',y:'elementY',width:'elementWidth',height:'elementHeight'})){const input=new Input(id);input.dataset.editorGeometry=key;input.parentElement=new Element();nodes.set('#'+id,input);geometry.push(input);}
  const names=['displayValue','unitLabel','selectedElement','editorBounds','sameSnapshot','cloneEditorElements','updateHistoryButtons','pushEditorHistory','restoreHistory','undoEditor','redoEditor','clampEditorElements','updateSelectedProperty','centerSelectedElement','setGeometryInputError','renderEditorGeometry','commitEditorGeometryInput','renderInspector','cancelLongPress','cancelEditorInteraction','closeTouchContextMenu','scheduleLongPress','startElementInteraction','moveElementInteraction','finishElementInteraction','nudgeSelected','handleEditorKeydown','focusLabelCanvas','snapMoveElement','pdfContentFingerprint','invalidateGeneratedPdf','refreshPdfValidity','hasPendingLayoutDrafts','resetLayoutDrafts','commitLayoutDrafts','setDisplayUnit','setSettings','setPage','invalidatePendingImports','applyProject'];
  for(const name of names){const body=functionSource(name);if(body)vm.runInContext(body,c);}
  c.renderLabelEditor=()=>{c.refreshPdfValidity();c.renderInspector();};c.render=()=>c.renderLabelEditor();c.clientToLabelPoint=e=>({x:e.x,y:e.y});
  for(const line of source.split('\n'))if(line.startsWith("      $$('[data-editor-geometry]').forEach(input=>")&&line.includes('addEventListener')||line.startsWith("      $('#centerHorizontalButton').addEventListener"))vm.runInContext(line,c);
  c.pushEditorHistory();c.renderInspector();
  function pdf(){c.outputState.sourceFingerprint=c.pdfContentFingerprint();c.outputState.generatedBlob={proof:true};return c.outputState.generation;}
  function drag(kind='move'){const target=new Element();target.dataset.elementId='original';if(kind==='resize')target.dataset.resizeHandle='se';c.startElementInteraction({pointerId:7,pointerType:'mouse',target,x:0,y:0,preventDefault(){}});}
  function pointer(type,x=5,y=1){c[type==='move'?'moveElementInteraction':'finishElementInteraction']({pointerId:7,type:type==='cancel'?'pointercancel':'pointer'+type,x,y,preventDefault(){}});}
  return {c,nodes,geometry,timers,pdf,drag,pointer,Element};
}
const almost=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-10,`${actual} != ${expected}`);
for(const type of ['text','image','qr','code128','code39'])for(const axis of ['x','y'])test(`${type} frame centers ${axis} without changing other fields or ordering`,()=>{const h=harness(),{c}=h;const element={...c.editorState.elements[0],type:type==='text'||type==='image'?type:'code',kind:type,sourceType:'field',fieldName:'name',value:'ABC',dataUrl:'synthetic-layout-only',width:17.135,height:9.625,hAlign:'right',vAlign:'bottom'};c.editorState.elements=[{...element,id:'before'},element,{...element,id:'after'}];c.editorState.history=[clone(c.editorState.elements)];c.editorState.historyIndex=0;const before=clone(c.editorState.elements),generation=h.pdf();c.centerSelectedElement(axis);const expected=clone(before);expected[1][axis]=((axis==='x'?66:33.9)-element[axis==='x'?'width':'height'])/2;assert.deepEqual(clone(c.editorState.elements),expected);assert.equal(c.editorState.selectedId,'original');assert.equal(c.editorState.history.length,2);assert.equal(c.outputState.generation,generation+1);assert.equal(c.outputState.generatedBlob,null);c.undoEditor();assert.deepEqual(clone(c.editorState.elements),before);c.redoEditor();assert.deepEqual(clone(c.editorState.elements),expected);});
for(const unit of ['mm','in'])for(const zoom of [50,300])test(`centering uses exact fractional mm at ${unit}/${zoom}% and ignores snap`,()=>{const h=harness(),{c}=h;c.unit=unit;c.editorState.zoom=zoom;c.editorState.snapEnabled=true;c.state.settings.labelWidth=31.537;c.state.settings.labelHeight=18.913;c.editorState.elements[0]=c.LabelEditorCore.resizeElement({...c.editorState.elements[0],x:1,y:2,width:10,height:5},'se',2.175,1.635,c.editorBounds());c.centerSelectedElement('x');c.centerSelectedElement('y');almost(c.selectedElement().x,(31.537-12.175)/2);almost(c.selectedElement().y,(18.913-6.635)/2);});
test('center buttons are localized real controls; no selection and same position retain PDF, redo and history',()=>{const h=harness(),{c}=h;for(const [id,key] of [['centerHorizontalButton','centerHorizontal'],['centerVerticalButton','centerVertical']])assert.match(source,new RegExp(`id="${id}"[^>]*type="button"[^>]*data-i18n="${key}"`));c.centerSelectedElement('x');c.centerSelectedElement('y');c.undoEditor();const history=clone(c.editorState.history),index=c.editorState.historyIndex,generation=h.pdf();c.$('#centerHorizontalButton').fire('click');assert.deepEqual(clone(c.editorState.history),history);assert.equal(c.editorState.historyIndex,index);assert.equal(c.outputState.generation,generation);assert.ok(c.outputState.generatedBlob);c.editorState.selectedId=null;c.renderInspector();assert.equal(c.$('#centerHorizontalButton').disabled,true);assert.equal(c.$('#centerVerticalButton').disabled,true);c.centerSelectedElement('y');assert.deepEqual(clone(c.editorState.history),history);assert.ok(c.outputState.generatedBlob);});
test('full-size frame on tiny label is already centered and never creates history',()=>{const h=harness(),{c}=h;c.state.settings.labelWidth=2.75;c.state.settings.labelHeight=1.25;c.editorState.elements[0]={...c.selectedElement(),x:0,y:0,width:2.75,height:1.25};c.editorState.history=[clone(c.editorState.elements)];c.editorState.historyIndex=0;h.pdf();c.centerSelectedElement('x');c.centerSelectedElement('y');assert.equal(c.editorState.history.length,1);assert.ok(c.outputState.generatedBlob);});
for(const key of ['x','y','width','height'])for(const bad of ['', '   ', '-', '1e', 'NaN','Infinity','1e999'])test(`invalid ${key} ${JSON.stringify(bad)} rolls back display without history or PDF changes`,()=>{const h=harness(),{c}=h,input=h.geometry.find(x=>x.dataset.editorGeometry===key),before=clone(c.editorState.elements),history=clone(c.editorState.history),generation=h.pdf();input.focus();input.value=bad;input.fire('input');assert.deepEqual(clone(c.editorState.elements),before);assert.equal(c.outputState.generation,generation);input.fire('change');input.fire('blur');assert.deepEqual(clone(c.editorState.elements),before);assert.deepEqual(clone(c.editorState.history),history);assert.ok(c.outputState.generatedBlob);assert.equal(c.outputState.generation,generation);assert.equal(input.value,c.displayValue(before[0][key]));assert.equal(input.getAttribute('aria-invalid'),'true');assert.ok(input.parentElement.querySelector('.layout-input-error')?.textContent);assert.equal(c.document.activeElement,input);});
for(const key of ['width','height'])for(const bad of ['0','-1'])test(`${key} rejects non-positive dimensions and accepts corrected mm/in once`,()=>{const h=harness(),{c}=h,input=h.geometry.find(x=>x.dataset.editorGeometry===key),before=clone(c.editorState.elements);h.pdf();input.value=bad;input.fire('change');assert.deepEqual(clone(c.editorState.elements),before);assert.ok(c.outputState.generatedBlob);for(const [unit,value,expected] of [['mm','20',20],['in','1',25.4]]){c.unit=unit;c.renderInspector();const history=c.editorState.history.length,generation=h.pdf();input.value=value;input.fire('input');input.fire('change');input.fire('blur');assert.equal(c.selectedElement()[key],expected);assert.equal(c.editorState.history.length,history+1);assert.equal(c.outputState.generation,generation+1);assert.equal(input.getAttribute('aria-invalid'),'false');}});
test('explicit coordinate zero is valid and intentional out-of-bounds input still clamps',()=>{const h=harness(),{c}=h;for(const key of ['x','y']){const input=h.geometry.find(x=>x.dataset.editorGeometry===key);input.value='0';input.fire('change');assert.equal(c.selectedElement()[key],0);}const input=h.geometry[0];input.value='10000';input.fire('change');assert.equal(c.selectedElement().x,66-c.selectedElement().width);});
test('focused input drafts survive unrelated render, and selection/unit changes clear stale feedback',()=>{const h=harness(),{c}=h,input=h.geometry[0];input.focus();input.value='';input.fire('input');c.renderInspector();assert.equal(input.value,'');input.fire('change');assert.equal(input.getAttribute('aria-invalid'),'true');c.editorState.elements.push({...c.selectedElement(),id:'second',x:5});c.editorState.selectedId='second';c.renderInspector();assert.equal(input.value,'5');assert.equal(input.getAttribute('aria-invalid'),'false');input.value='';input.fire('change');c.setDisplayUnit('in');assert.equal(input.getAttribute('aria-invalid'),'false');assert.equal(input.value,c.displayValue(5));});
for(const action of ['undo','redo'])for(const kind of ['move','resize'])test(`${action} during ${kind} retires pointer/long-press and old events cannot mutate restored history`,()=>{const h=harness(),{c}=h;c.updateSelectedProperty('x',3,{commit:true});if(action==='redo')c.undoEditor();h.drag(kind);h.pointer('move',4,2);c.editorState.longPress={pointerId:7,timer:c.setTimeout(()=>{},50)};c[action+'Editor']();const restored=clone(c.editorState.elements),history=clone(c.editorState.history);assert.equal(c.editorState.interaction,null);assert.equal(c.editorState.longPress,null);assert.equal(h.timers.size,0);assert.equal(c.$('#labelEditorSvg').capture,null);h.pointer('move',6,4);h.pointer('up');assert.deepEqual(clone(c.editorState.elements),restored);assert.deepEqual(clone(c.editorState.history),history);});
for(const boundary of ['reset','project','escape','page'])test(`${boundary} retires old interaction without storing partial drag`,()=>{const h=harness(),{c}=h,before=clone(c.editorState.elements);h.drag();h.pointer('move');if(boundary==='reset')c.setSettings(c.defaultSettings);if(boundary==='project')c.applyProject(c.ProjectFileCore.createProject({settings:c.defaultSettings,elements:before,data:{},sheet:{},output:{}}));if(boundary==='escape'){const target=new h.Element();target.editor=true;c.handleEditorKeydown({target,key:'Escape',preventDefault(){}});}if(boundary==='page')c.setPage('paperPage');const restored=clone(c.editorState.elements),history=clone(c.editorState.history);assert.deepEqual(restored,before);h.pointer('move',8,6);h.pointer('up');assert.deepEqual(clone(c.editorState.elements),restored);assert.deepEqual(clone(c.editorState.history),history);assert.equal(c.editorState.interaction,null);});
test('normal completed drag/resize and pointercancel retain existing history behavior',()=>{for(const kind of ['move','resize'])for(const end of ['up','cancel']){const h=harness(),{c}=h,before=clone(c.editorState.elements);h.drag(kind);h.pointer('move');h.pointer(end);const after=clone(c.editorState.elements);assert.notDeepEqual(after,before);assert.equal(c.editorState.history.length,2);c.undoEditor();assert.deepEqual(clone(c.editorState.elements),before);c.redoEditor();assert.deepEqual(clone(c.editorState.elements),after);}});
for(const sourceType of ['fixed','field'])test(`completed clicks still allow desktop double-click ${sourceType} text editing`,()=>{const h=harness(),{c}=h;c.selectedElement().sourceType=sourceType;let edits=0;c.focusSelectedTextEditor=()=>edits++;h.drag();h.pointer('up',0,0);h.drag();assert.equal(edits,1);assert.equal(c.editorState.interaction,null);});
for(const boundary of ['escape','page','reset'])test(`drag then keyboard nudge before ${boundary} commits only the nudge`,()=>{const h=harness(),{c}=h,before=clone(c.editorState.elements);h.drag();h.pointer('move',5,1);const target=new h.Element();target.editor=true;c.handleEditorKeydown({target,key:'ArrowRight',preventDefault(){}});const expected=clone(before);expected[0].x+=.2;assert.deepEqual(clone(c.editorState.elements),expected);assert.equal(c.editorState.interaction,null);if(boundary==='escape')c.handleEditorKeydown({target,key:'Escape',preventDefault(){}});if(boundary==='page')c.setPage('paperPage');if(boundary==='reset')c.setSettings(c.defaultSettings);h.pointer('move',9,3);h.pointer('up');assert.deepEqual(clone(c.editorState.elements),expected);assert.deepEqual(clone(c.editorState.history[c.editorState.historyIndex]),expected);c.undoEditor();assert.deepEqual(clone(c.editorState.elements),before);c.redoEditor();assert.deepEqual(clone(c.editorState.elements),expected);});
for(const action of ['updateSelectedProperty','duplicateSelectedElement','deleteSelectedElement','bringSelectedFront','sendSelectedBack'])test(`${action} retires a pending drag before committing`,()=>{const h=harness(),{c}=h,before=clone(c.editorState.elements);c.editorIdCounter=1;for(const name of ['newEditorId','duplicateSelectedElement','deleteSelectedElement','bringSelectedFront','sendSelectedBack'])vm.runInContext(functionSource(name),c);h.drag();h.pointer('move',5,1);if(action==='updateSelectedProperty')c.updateSelectedProperty('text','Edited',{commit:true});else c[action]();assert.equal(c.editorState.interaction,null);for(const element of c.editorState.elements.filter(e=>e.id==='original'))assert.equal(element.x,before[0].x);if(action==='deleteSelectedElement')assert.equal(c.editorState.deletedSnapshot.element.x,before[0].x);const committed=clone(c.editorState.elements),history=clone(c.editorState.history);c.cancelEditorInteraction();h.pointer('move',7,1);h.pointer('up');assert.deepEqual(clone(c.editorState.elements),committed);assert.deepEqual(clone(c.editorState.history),history);assert.deepEqual(clone(c.editorState.history[c.editorState.historyIndex]),committed);});
for(const [name,arg] of [['addTextElement'],['addCodeElement','qr'],['addDataFieldElement','name']])test(`${name} abandons partial drag before adding a new selection`,()=>{const h=harness(),{c}=h,before=clone(c.editorState.elements);c.editorIdCounter=1;for(const fn of ['newEditorId',name])vm.runInContext(functionSource(fn),c);h.drag();h.pointer('move');c[name](arg);assert.equal(c.editorState.interaction,null);assert.equal(c.editorState.elements[0].x,before[0].x);const committed=clone(c.editorState.elements);c.cancelEditorInteraction();h.pointer('move',7,1);h.pointer('up');assert.deepEqual(clone(c.editorState.elements),committed);assert.deepEqual(clone(c.editorState.history[c.editorState.historyIndex]),committed);});
